# Generated by Django 3.2.4 on 2021-06-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_id',
            field=models.IntegerField(max_length=20),
        ),
    ]
